#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: service-statistics #配置service-statistics服务
#          uri: lb://service-statistics
#          predicates:
#            - Path=/staservice/** # 路径匹配
#        - id: service-vod #配置service-vod服务
#          uri: lb://service-vod
#          predicates:
#            - Path=/eduvod/** # 路径匹配
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848

#server:
#  port: 8222
